### PR TITLE
Basic functionality of podman-desktop

### PR DESCRIPTION
**Pull request by ashley-cui**
Still needs HEAVY editing for error handing and state wrestling and window management.

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Remove the WIP and Draft and we can merge.  Update the README with you Work In Progress stuff.

It is understood that this is not V1.0 but more like v0.01

**Comment by ashley-cui** [comment]
Sure, let me update that

**Comment by rhatdan** [comment]
Remove [WIP] from the commit message.  You can change it to "initial version"

**Comment by ashley-cui** [comment]
Okay, lets get in the gitignore before this, I want to make sure I'm not including any userdata

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
